### ISSUE TITLE
a question about your code

### ISSUE THREAD

**Issue by laulampaul** [gfacciol/CDM-CNN_pytorch#1]
In the paper, in the last layer of first stage, RG and B channel pass through different conv layer, but in your code ,they pass through the same layer.

**Comment by gfacciol** [comment]
That's correct, however the data is split in RB - G just to be regrouped afterwards. 
The computational graph below illustrates that point. 

![image](https://user-images.githubusercontent.com/5002346/64260006-703af980-cf2a-11e9-9f45-a58a4e330d38.png)

So the two conv layers 112G and 112RB can be joined in a single layer with a 3-channel output:
The whole network is depicted here:

![image](https://user-images.githubusercontent.com/5002346/64259917-497cc300-cf2a-11e9-9147-f3789e97e35e.png)
